export const SET_CURRENT_USER = 'SET_CURRENT-USER';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const SET_CURRENT_OWNER_ROLE = 'SET_CURRENT_OWNER_ROLE';
export const LOGOUT_USER = 'LOGOUT_USER';